# Generated by Django 5.2.13 on 2026-04-21 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_m3', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('billing_due_days', models.PositiveIntegerField(default=15)),
                ('enable_cash_payments', models.BooleanField(default=True)),
                ('enable_online_payments', models.BooleanField(default=True)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('notify_by_sms', models.BooleanField(default=False)),
                ('payment_gateway_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('reader', 'Reading Panel'), ('consumer', 'Consumer')], default='consumer', max_length=20),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(default=django.utils.timezone.localdate)),
                ('billing_month', models.DateField(editable=False)),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='billing.consumer')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_meter_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=20)),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('bill_due', 'Bill Due'), ('payment', 'Payment'), ('reading', 'Meter Reading'), ('admin', 'Admin')], default='general', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='billing.billingrecord')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='billing.consumer')),
                ('meter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='billing.meterreading')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='billing.payment')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSBlast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('all_active', 'All Active Consumers'), ('overdue', 'Consumers With Overdue Bills'), ('pending', 'Consumers With Pending Bills')], default='all_active', max_length=30)),
                ('message', models.TextField()),
                ('provider', models.CharField(default='twilio', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('recipients_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_blasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('consumer', 'billing_month'), name='unique_monthly_meter_reading'),
        ),
    ]
