# Generated by Django 5.2.13 on 2026-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_promote_staff_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online Payment'), ('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('bank', 'Bank')], default='cash', max_length=20),
        ),
    ]
