# Generated by Django 5.2.13 on 2026-04-26 00:32

from django.db import migrations, models


def backfill_payment_covered_month(apps, schema_editor):
    Payment = apps.get_model('billing', 'Payment')

    for payment in Payment.objects.select_related('billing').all():
        if payment.billing_id and payment.billing and payment.billing.billing_month:
            payment.covered_month = payment.billing.billing_month.replace(day=1)
        elif payment.payment_date:
            payment.covered_month = payment.payment_date.replace(day=1)
        payment.save(update_fields=['covered_month'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_paymongo_gateway_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='covered_month',
            field=models.DateField(blank=True, help_text='Use the first day of the covered month.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_payment_covered_month, migrations.RunPython.noop),
    ]
