# Generated by Django 5.2.13 on 2026-05-20 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_billingrecord_penalty_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('delinquent', 'Delinquent'), ('for_disconnection', 'For Disconnection'), ('disconnected', 'Disconnected')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='consumer',
            name='disconnection_scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='last_payment_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='warning_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_water_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='arrangement_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_scope',
            field=models.CharField(choices=[('bulk', 'Bulk Settlement'), ('selective', 'Selective Settlement')], default='bulk', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement_type', models.CharField(choices=[('selective', 'Selective Monthly Settlement'), ('payment_plan', 'Payment Arrangement')], default='selective', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('selected_billings', models.JSONField(blank=True, default=list)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outstanding_balance_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_balance_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_arrangements', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_arrangements', to='billing.consumer')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrangement', to='billing.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payment_arrangements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisconnectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('monitoring', 'Monitoring'), ('for_disconnection', 'For Disconnection'), ('disconnected', 'Disconnected'), ('cancelled', 'Cancelled')], default='monitoring', max_length=30)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unpaid_months_count', models.PositiveIntegerField(default=0)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_disconnection_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_disconnection_records', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_records', to='billing.consumer')),
                ('arrangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnection_records', to='billing.paymentarrangement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
