# Generated by Django 5.2.13 on 2026-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_consumer_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
