# Generated by Django 5.2.13 on 2026-05-21 07:53

import re

from django.db import migrations, models
from django.utils.crypto import get_random_string


def _meter_prefix(full_name):
    parts = [segment for segment in re.split(r'\s+', str(full_name or '').strip()) if segment]
    particles = {'DE', 'DELA', 'DEL', 'DELOS', 'DELAS', 'VAN', 'VON', 'SAN', 'SANTA', 'STA'}
    if parts:
        selected = [parts[-1]]
        index = len(parts) - 2
        while index >= 0 and re.sub(r'[^A-Za-z0-9]', '', parts[index]).upper() in particles:
            selected.insert(0, parts[index])
            index -= 1
        seed = ''.join(selected)
    else:
        seed = 'CONSUMER'
    normalized = re.sub(r'[^A-Za-z0-9]', '', seed).upper()
    return normalized[:12] or 'CONSUMER'


def populate_meter_numbers(apps, schema_editor):
    Consumer = apps.get_model('billing', 'Consumer')
    allowed = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'

    for consumer in Consumer.objects.filter(meter_number=''):
        prefix = _meter_prefix(consumer.full_name)
        while True:
            candidate = f'{prefix}-MTR-{get_random_string(5, allowed)}'
            if not Consumer.objects.exclude(pk=consumer.pk).filter(meter_number=candidate).exists():
                consumer.meter_number = candidate
                consumer.save(update_fields=['meter_number'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_payment_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='barangay',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consumer',
            name='household_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consumer',
            name='meter_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='consumer',
            name='village',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AreaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('household', 'Household'), ('village', 'Village'), ('barangay', 'Barangay')], max_length=20)),
                ('location_name', models.CharField(max_length=120)),
                ('rate_per_m3', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'location_name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'location_name'), name='unique_area_rate_category_location')],
            },
        ),
        migrations.RunPython(populate_meter_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='consumer',
            name='meter_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
