from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.RoleBasedLoginView.as_view(), name='login'),
    path('login/google/', views.google_login_start, name='google_login_start'),
    path('login/google/callback/', views.google_login_callback, name='google_login_callback'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/admin/', views.admin_panel, name='admin_panel'),
    path('dashboard/admin/data/', views.admin_panel_data, name='admin_panel_data'),
    path('dashboard/secretary/', views.secretary_panel, name='secretary_panel'),
    path('dashboard/secretary/data/', views.secretary_panel_data, name='secretary_panel_data'),
    path('dashboard/secretary/minutes/<int:minutes_id>/', views.secretary_meeting_minutes_detail, name='secretary_meeting_minutes_detail'),
    path('dashboard/secretary/minutes/<int:minutes_id>/export/', views.secretary_meeting_minutes_export_pdf, name='secretary_meeting_minutes_export_pdf'),
    path('dashboard/treasurer/', views.treasurer_panel, name='treasurer_panel'),
    path('dashboard/treasurer/data/', views.treasurer_panel_data, name='treasurer_panel_data'),
    path('dashboard/reader/', views.reader_panel, name='reader_panel'),
    path('dashboard/reader/data/', views.reader_panel_data, name='reader_panel_data'),
    path('dashboard/reader/submit/', views.submit_reader_reading, name='submit_reader_reading'),
    path('dashboard/reader/context/', views.reader_reading_context, name='reader_reading_context'),
    path('dashboard/reader/readings/<int:reading_id>/update/', views.update_reader_reading, name='update_reader_reading'),
    path('dashboard/consumer/', views.consumer_panel, name='consumer_panel'),
    path('dashboard/consumer/data/', views.consumer_panel_data, name='consumer_panel_data'),
    path('dashboard/consumer/account/', views.account_center, name='account_center'),
    path('payments/paymongo/<int:payment_id>/success/', views.paymongo_success, name='paymongo_success'),
    path('payments/paymongo/<int:payment_id>/verify/', views.paymongo_verify, name='paymongo_verify'),
    path('payments/paymongo/<int:payment_id>/cancel/', views.paymongo_cancel, name='paymongo_cancel'),
    path('payments/<int:payment_id>/receipt/', views.payment_receipt_view, name='payment_receipt'),
    path('consumers/', views.consumer_list, name='consumers'),
    path('consumers/add/', views.add_consumer, name='add_consumer'),
    path('consumers/<int:consumer_id>/edit/', views.edit_consumer, name='edit_consumer'),
    path('billing/', views.billing_list, name='billing'),
    path('billing/add/', views.add_billing, name='add_billing'),
    path('payments/', views.payments_list, name='payments'),
    path('payments/<int:payment_id>/status/', views.update_payment_status_view, name='update_payment_status'),
    path('payments/<int:payment_id>/notify/', views.notify_payment_status, name='notify_payment_status'),
    path('staff-accounts/<int:profile_id>/status/', views.update_staff_account_status, name='update_staff_account_status'),
    path('reports/', views.reports_view, name='reports'),
    path('reports/export/', views.reports_export_view, name='reports_export'),
    path('communications/', views.communications_view, name='communications'),
    path('settings/payments/', views.payment_settings_view, name='payment_settings'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.update_profile_view, name='update_profile'),
]
